config/routes.rb
Rails.application.routes.draw do

  resources :auth_providers

  get 'friendships/requests' => 'friendships#requests', format: 'json'
  get 'friendships/requested' => 'friendships#requested', format: 'json'
  get 'friendships/:id/accept' => 'friendships#accept', format: 'json'
  resources :friendships

  post 'devices/' => 'devices#create', format: 'json'

  get 'friends/facebook' => 'friends#facebook', format: 'json'
  get 'friends/' => 'friends#index', format: 'json'
  get 'verbs' => 'verbs#index', format: 'json'
  get 'activities/' => 'activities#index', format: 'json'

  root 'sessions#show', format: 'json'
  get 'user' => 'sessions#show', format: 'json'
  post 'login' => 'sessions#login', format: 'json'
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'logout', to: 'sessions#destroy', as: 'logout', via: [:get, :post]

  post 'users' => 'users#create', format: 'json'

  get 'messages', to: redirect('activities')
  get 'messages/sent' => 'messages#sent'
  get 'messages/received' => 'messages#received'
  get 'messages/:id/acknowledge' => 'messages#acknowledge'
  get 'messages/:id/reciprocate' => 'messages#reciprocate'

  resources :messages

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'

  has_many :activities, as: :actionable, dependent: :destroy
  has_one :sender_activity, ->(message) { where type: 'sent', actionable_id: message.id, actionable_type: 'Message' }, class_name: 'Activity'
  has_one :recipient_activity, ->(message) { where type: 'received', actionable_id: message.id, actionable_type: 'Message' }, class_name: 'Activity'

  after_create :create_activity_entries
  after_save do
    Librato.increment 'messages.sent'
  end

  # Let's at least try to keep the db nice and tidy.
  validates :sender, :recipient, :verb, presence: true
  validates :id, absence: true, on: :create

  def self.sent_by(user)
    where sender: user
  end

  def self.sent_to(user)
    where recipient: user
  end

  def acknowledge
    update acknowledged_at: Time.now
    notify_acknowledgement
    Librato.increment 'messages.acknowledged'
  end

  def self.reciprocate(original_message)
    new_message = Message.create sender: original_message.recipient, recipient: original_message.sender, verb: original_message.verb
    Librato.increment 'messages.reciprocated'
    new_message
  end

  private

  def create_activity_entries
    Activity.activities_for_message self
  end

  # Notify sender that message was ack'd
  def notify_acknowledgement
    # message = sender_activity.decorate.activity_message
    # logger.info "Preparing to send acknowledgment push notification of #{ message } to sender: #{ sender.id }"
    #
    # sender.devices.each do |device|
    #   device.notify message
    # end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy, :acknowledge, :reciprocate]

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new sender: current_user
  end

  # GET /messages/1/edit
  def edit
  end

  # GET /messages/sent
  # GET /messages/sent.json
  def sent
    @messages = Message.sent_by current_user
  end

  # GET /messages/received
  # GET /messages/received.json
  def received
    @messages = Message.sent_to current_user
  end

  # GET /messages/1/acknowledge
  def acknowledge
    @message.acknowledge
  end

  # GET /messages/1/reciprocate
  def reciprocate
    @message = Message.reciprocate @message
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new sender_id: current_user.id, recipient_id: message_params[:recipient_id], verb: message_params[:verb]

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_message
    @message = Message.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def message_params
    params.require(:message).permit(:recipient_id, :verb)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :recipient_id %><br>
    <%= f.number_field :recipient_id %>
  </div>
  <div class="field">
    <%= f.label :verb %><br>
    <%= f.text_area :verb %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/acknowledge.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sender:</strong>
  <%= @message.sender_id %>
</p>

<p>
  <strong>Recipient:</strong>
  <%= @message.recipient_id %>
</p>

<p>
  <strong>Acknowledged at:</strong>
  <%= @message.acknowledged_at %>
</p>

<p>
  <strong>Verb:</strong>
  <%= @message.verb %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <thead>
    <tr>
      <th>Sender</th>
      <th>Recipient</th>
      <th>Acknowledged at</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.sender_id %></td>
        <td><%= message.recipient_id %></td>
        <td><%= message.acknowledged_at %></td>
        <td><%= message.body %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/received.html.erb
<h1>Received messages</h1>

<table>
  <thead>
    <tr>
      <th>Sender</th>
      <th>Recipient</th>
      <th>Acknowledged at</th>
      <th>Verb</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.sender_id %></td>
        <td><%= message.recipient_id %></td>
        <td><%= message.acknowledged_at %></td>
        <td><%= message.verb %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/reciprocate.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sender:</strong>
  <%= @message.sender_id %>
</p>

<p>
  <strong>Recipient:</strong>
  <%= @message.recipient_id %>
</p>

<p>
  <strong>Acknowledged at:</strong>
  <%= @message.acknowledged_at %>
</p>

<p>
  <strong>Verb:</strong>
  <%= @message.verb %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/messages/sent.html.erb
<h1>Sent messages</h1>

<table>
  <thead>
    <tr>
      <th>Sender</th>
      <th>Recipient</th>
      <th>Acknowledged at</th>
      <th>Verb</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.sender_id %></td>
        <td><%= message.recipient_id %></td>
        <td><%= message.acknowledged_at %></td>
        <td><%= message.verb %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sender:</strong>
  <%= @message.sender_id %>
</p>

<p>
  <strong>Recipient:</strong>
  <%= @message.recipient_id %>
</p>

<p>
  <strong>Acknowledged at:</strong>
  <%= @message.acknowledged_at %>
</p>

<p>
  <strong>Verb:</strong>
  <%= @message.verb %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>