config/routes.rb
Rails.application.routes.draw do

  resources :auth_providers

  get 'friendships/requests' => 'friendships#requests', format: 'json'
  get 'friendships/requested' => 'friendships#requested', format: 'json'
  get 'friendships/:id/accept' => 'friendships#accept', format: 'json'
  resources :friendships

  post 'devices/' => 'devices#create', format: 'json'

  get 'friends/facebook' => 'friends#facebook', format: 'json'
  get 'friends/' => 'friends#index', format: 'json'
  get 'verbs' => 'verbs#index', format: 'json'
  get 'activities/' => 'activities#index', format: 'json'

  root 'sessions#show', format: 'json'
  get 'user' => 'sessions#show', format: 'json'
  post 'login' => 'sessions#login', format: 'json'
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'logout', to: 'sessions#destroy', as: 'logout', via: [:get, :post]

  post 'users' => 'users#create', format: 'json'

  get 'messages', to: redirect('activities')
  get 'messages/sent' => 'messages#sent'
  get 'messages/received' => 'messages#received'
  get 'messages/:id/acknowledge' => 'messages#acknowledge'
  get 'messages/:id/reciprocate' => 'messages#reciprocate'

  resources :messages

end

app/models/friendship.rb
include ActiveModel::Validations

class FriendshipValidator < ActiveModel::Validator
  def validate(record)
    relationships = Friendship.any_friendships record.user, record.friend
    record.errors.add(:base, 'You are already friends, or there is a pending friend request between you.') if relationships.count > 0
  end
end

class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User'
  has_many :activities, as: :actionable, dependent: :destroy

  after_create :create_activity_entries

  validates_with FriendshipValidator, on: :create
  validate :user_cannot_friend_themselves

  def user_cannot_friend_themselves
    errors.add(:friend_id, 'cannot be same as user - stop trying to friend yourself.') if user_id == friend_id
  end

  def accept
    update approved: Time.now
  end

  def self.any_friendships(user, friend)
    # Get any and all friendships linking two users.
    Friendship.where(user: user, friend: friend) + Friendship.where(user: friend, friend: user)
  end

  private

  def create_activity_entries
    Activity.activities_for_friendship self
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :edit, :update, :destroy, :accept]

  # GET /friendships
  # GET /friendships.json
  def index
    @friendships = current_user.friendships + current_user.inverse_friendships
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show
  end

  # GET /friendships/new
  def new
    @friendship = Friendship.new user: current_user
  end

  # GET /friendships/1/edit
  def edit
  end

  # GET /friendships/1/accept
  def accept
    # Can only accept requests sent to current_user
    if @friendship.friend == current_user
      @friendship.accept
      render :show, status: :ok
    else
      render json: @friendship.errors, status: :unprocessable_entity
    end
  end

  # GET /friendships/requests
  def requests
    @friendships = current_user.friendship_requests_received
  end

  # GET /friendships/requested
  def requested
    @friendships = current_user.friendship_requests_sent
  end

  # POST /friendships
  # POST /friendships.json
  def create
    @friendship = Friendship.new(user: current_user, friend_id: friendship_params[:friend_id])

    respond_to do |format|
      if @friendship.save
        format.html { redirect_to @friendship, notice: 'Friendship was successfully created.' }
        format.json { render :show, status: :created, location: @friendship }
      else
        format.html { render :new }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friendships/1
  # PATCH/PUT /friendships/1.json
  def update
    respond_to do |format|
      if @friendship.update(friendship_params)
        format.html { redirect_to @friendship, notice: 'Friendship was successfully updated.' }
        format.json { render :show, status: :ok, location: @friendship }
      else
        format.html { render :edit }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    @friendship.destroy
    respond_to do |format|
      format.html { redirect_to friendships_url, notice: 'Friendship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_friendship
    @friendship = Friendship.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def friendship_params
    params.require(:friendship).permit(:friend_id)
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :friend_id %><br>
    <%= f.number_field :friend_id %>
  </div>
  <div class="field">
    <%= f.label :approved %><br>
    <%= f.datetime_select :approved %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<h1>Listing friendships</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Friend</th>
      <th>Approved</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friendships.each do |friendship| %>
      <tr>
        <td><%= friendship.user_id %></td>
        <td><%= friendship.friend_id %></td>
        <td><%= friendship.approved %></td>
        <td><%= link_to 'Show', friendship %></td>
        <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
        <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @friendship.user_id %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friendship.friend_id %>
</p>

<p>
  <strong>Approved:</strong>
  <%= @friendship.approved %>
</p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>