config/routes.rb
Rails.application.routes.draw do

  resources :auth_providers

  get 'friendships/requests' => 'friendships#requests', format: 'json'
  get 'friendships/requested' => 'friendships#requested', format: 'json'
  get 'friendships/:id/accept' => 'friendships#accept', format: 'json'
  resources :friendships

  post 'devices/' => 'devices#create', format: 'json'

  get 'friends/facebook' => 'friends#facebook', format: 'json'
  get 'friends/' => 'friends#index', format: 'json'
  get 'verbs' => 'verbs#index', format: 'json'
  get 'activities/' => 'activities#index', format: 'json'

  root 'sessions#show', format: 'json'
  get 'user' => 'sessions#show', format: 'json'
  post 'login' => 'sessions#login', format: 'json'
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'logout', to: 'sessions#destroy', as: 'logout', via: [:get, :post]

  post 'users' => 'users#create', format: 'json'

  get 'messages', to: redirect('activities')
  get 'messages/sent' => 'messages#sent'
  get 'messages/received' => 'messages#received'
  get 'messages/:id/acknowledge' => 'messages#acknowledge'
  get 'messages/:id/reciprocate' => 'messages#reciprocate'

  resources :messages

end

app/models/auth_provider.rb
class AuthProvider < ActiveRecord::Base
  belongs_to :user

  def self.from_omniauth(auth)
    provider = where(uid: auth.uid, provider: auth.provider).first_or_initialize.tap do |auth_provider|
      auth_provider.provider = auth.provider
      auth_provider.uid = auth.uid

      auth_provider.token = auth.credentials.token
      auth_provider.secret = auth.credentials.secret if auth.credentials.secret
      auth_provider.token_expiration = Time.at(auth.credentials.expires_at) if auth.credentials.expires_at

      auth_provider.nickname = auth.info.nickname if auth.info.nickname
      auth_provider.last_used = Time.now

      auth_provider.save!
    end

    # Ensure auth token is up to date.
    if provider.token != auth.credentials.token
      logger.warn 'Updating user token'
      provider.update token: auth.credentials.token
    end

    provider
  end
end

app/controllers/auth_providers_controller.rb
class AuthProvidersController < ApplicationController
  before_action :set_auth_provider, only: [:show, :edit, :update, :destroy]

  # GET /auth_providers
  # GET /auth_providers.json
  def index
    @auth_providers = AuthProvider.all
  end

  # GET /auth_providers/1
  # GET /auth_providers/1.json
  def show
  end

  # GET /auth_providers/new
  def new
    @auth_provider = AuthProvider.new
  end

  # GET /auth_providers/1/edit
  def edit
  end

  # POST /auth_providers
  # POST /auth_providers.json
  def create
    @auth_provider = AuthProvider.new(auth_provider_params)

    respond_to do |format|
      if @auth_provider.save
        format.html { redirect_to @auth_provider, notice: 'Auth provider was successfully created.' }
        format.json { render :show, status: :created, location: @auth_provider }
      else
        format.html { render :new }
        format.json { render json: @auth_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auth_providers/1
  # PATCH/PUT /auth_providers/1.json
  def update
    respond_to do |format|
      if @auth_provider.update(auth_provider_params)
        format.html { redirect_to @auth_provider, notice: 'Auth provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @auth_provider }
      else
        format.html { render :edit }
        format.json { render json: @auth_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auth_providers/1
  # DELETE /auth_providers/1.json
  def destroy
    @auth_provider.destroy
    respond_to do |format|
      format.html { redirect_to auth_providers_url, notice: 'Auth provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_auth_provider
    @auth_provider = AuthProvider.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def auth_provider_params
    params.require(:auth_provider).permit(:user_id, :provider, :uid, :nickname, :token, :secret, :token_expiration, :last_used)
  end
end

app/helpers/auth_providers_helper.rb
module AuthProvidersHelper
end

app/views/auth_providers/_form.html.erb
<%= form_for(@auth_provider) do |f| %>
  <% if @auth_provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auth_provider.errors.count, "error") %> prohibited this auth_provider from being saved:</h2>

      <ul>
      <% @auth_provider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :provider %><br>
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :uid %><br>
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :nickname %><br>
    <%= f.text_field :nickname %>
  </div>
  <div class="field">
    <%= f.label :token %><br>
    <%= f.text_field :token %>
  </div>
  <div class="field">
    <%= f.label :secret %><br>
    <%= f.text_field :secret %>
  </div>
  <div class="field">
    <%= f.label :token_expiration %><br>
    <%= f.datetime_select :token_expiration %>
  </div>
  <div class="field">
    <%= f.label :last_used %><br>
    <%= f.datetime_select :last_used %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/auth_providers/edit.html.erb
<h1>Editing auth_provider</h1>

<%= render 'form' %>

<%= link_to 'Show', @auth_provider %> |
<%= link_to 'Back', auth_providers_path %>

app/views/auth_providers/index.html.erb
<h1>Listing auth_providers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Provider</th>
      <th>Uid</th>
      <th>Nickname</th>
      <th>Token</th>
      <th>Secret</th>
      <th>Token expiration</th>
      <th>Last used</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @auth_providers.each do |auth_provider| %>
      <tr>
        <td><%= auth_provider.user_id %></td>
        <td><%= auth_provider.provider %></td>
        <td><%= auth_provider.uid %></td>
        <td><%= auth_provider.nickname %></td>
        <td><%= auth_provider.token %></td>
        <td><%= auth_provider.secret %></td>
        <td><%= auth_provider.token_expiration %></td>
        <td><%= auth_provider.last_used %></td>
        <td><%= link_to 'Show', auth_provider %></td>
        <td><%= link_to 'Edit', edit_auth_provider_path(auth_provider) %></td>
        <td><%= link_to 'Destroy', auth_provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Auth provider', new_auth_provider_path %>

app/views/auth_providers/new.html.erb
<h1>New auth_provider</h1>

<%= render 'form' %>

<%= link_to 'Back', auth_providers_path %>

app/views/auth_providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @auth_provider.user_id %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @auth_provider.provider %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @auth_provider.uid %>
</p>

<p>
  <strong>Nickname:</strong>
  <%= @auth_provider.nickname %>
</p>

<p>
  <strong>Token:</strong>
  <%= @auth_provider.token %>
</p>

<p>
  <strong>Secret:</strong>
  <%= @auth_provider.secret %>
</p>

<p>
  <strong>Token expiration:</strong>
  <%= @auth_provider.token_expiration %>
</p>

<p>
  <strong>Last used:</strong>
  <%= @auth_provider.last_used %>
</p>

<%= link_to 'Edit', edit_auth_provider_path(@auth_provider) %> |
<%= link_to 'Back', auth_providers_path %>